"""
Git Repository Activity Reporter.

This module analyzes the commit history of a Git repository and generates
two JSON reports:

1. An author activity report.
2. A repository activity summary.

The analysis includes commit metadata, author information, remote branch
membership, and commit activity within a configurable time period.
"""

import argparse
import json
import shlex
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any


# ============================================================
# Configuration
# ============================================================

DEFAULT_ANALYSIS_DAYS = 65

DEFAULT_AUTHORS_OUTPUT = "authors.json"
DEFAULT_REPOSITORY_OUTPUT = "repository.json"

REMOTE_NAME = "origin"
REMOTE_REFS = f"refs/remotes/{REMOTE_NAME}"

NO_REMOTE_BRANCH = "no_remote_branch"


# Generic type used for JSON-compatible dictionaries.
JsonDict = dict[str, Any]


# ============================================================
# Git Utilities
# ============================================================

def run_git(
    repository: Path,
    arguments: list[str],
) -> str:
    """
    Execute a Git command inside the specified repository.

    Args:
        repository: Path to the Git repository.
        arguments: Git command arguments.

    Returns:
        Standard output generated by Git.

    Raises:
        RuntimeError: If the Git command finishes with a non-zero
            exit status.
    """

    command = [
        "git",
        "-C",
        str(repository),
        *arguments,
    ]

    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )

    if result.returncode != 0:
        readable_command = shlex.join(command)

        raise RuntimeError(
            "Git command failed.\n\n"
            f"Command:\n{readable_command}\n\n"
            f"Git output:\n{result.stderr.strip()}"
        )

    return result.stdout.strip()


def normalize_remote_branches(
    output: str,
) -> list[str]:
    """
    Normalize and filter remote branch names returned by Git.

    Symbolic HEAD references such as ``origin/HEAD`` are excluded
    because they are not actual repository branches.

    Args:
        output: Raw Git output containing one branch per line.

    Returns:
        Sorted list of unique remote branches.
    """

    branches = []

    for branch in output.splitlines():
        branch = branch.strip()

        if not branch:
            continue

        if branch == f"{REMOTE_NAME}/HEAD":
            continue

        if branch.endswith("/HEAD"):
            continue

        branches.append(branch)

    return sorted(set(branches))


# ============================================================
# Repository Information
# ============================================================

def get_remote_branches(
    repository: Path,
) -> list[str]:
    """
    Return all available remote branches.

    Args:
        repository: Path to the Git repository.

    Returns:
        Sorted list of remote branch names.
    """

    output = run_git(
        repository,
        [
            "for-each-ref",
            "--format=%(refname:short)",
            REMOTE_REFS,
        ],
    )

    return normalize_remote_branches(output)


def get_commits_in_period(
    repository: Path,
    days: int,
) -> list[str]:
    """
    Return commits reachable from all downloaded references within
    the requested analysis period.

    Duplicate hashes are removed in case the same commit is reachable
    from multiple branches.

    Args:
        repository: Path to the Git repository.
        days: Number of previous days to analyze.

    Returns:
        List of unique commit hashes.
    """

    output = run_git(
        repository,
        [
            "rev-list",
            "--all",
            f"--since={days} days ago",
        ],
    )

    if not output:
        return []

    return list(
        dict.fromkeys(output.splitlines())
    )


def get_total_commit_count(
    repository: Path,
) -> int:
    """
    Count all commits reachable from the downloaded references.

    Args:
        repository: Path to the Git repository.

    Returns:
        Total number of reachable commits.
    """

    output = run_git(
        repository,
        [
            "rev-list",
            "--all",
            "--count",
        ],
    )

    return int(output or 0)


# ============================================================
# Commit Information
# ============================================================

def get_commit_metadata(
    repository: Path,
    commit_hash: str,
) -> dict[str, str]:
    """
    Retrieve the main metadata associated with a commit.

    Args:
        repository: Path to the Git repository.
        commit_hash: Full or abbreviated Git commit hash.

    Returns:
        Dictionary containing the commit hash, short hash, author,
        email, author date, and commit message.

    Raises:
        RuntimeError: If the Git output cannot be parsed.
    """

    separator = "\x1f"

    output = run_git(
        repository,
        [
            "show",
            "-s",
            (
                f"--format=%H{separator}"
                f"%h{separator}"
                f"%an{separator}"
                f"%ae{separator}"
                f"%aI{separator}"
                "%s"
            ),
            commit_hash,
        ],
    )

    parts = output.split(
        separator,
        maxsplit=5,
    )

    if len(parts) != 6:
        raise RuntimeError(
            "Unable to parse commit metadata for "
            f"{commit_hash}."
        )

    return {
        "hash": parts[0],
        "short_hash": parts[1],
        "author": parts[2],
        "email": parts[3].lower().strip(),
        "date": parts[4],
        "message": parts[5],
    }


def get_commit_remote_branches(
    repository: Path,
    commit_hash: str,
) -> list[str]:
    """
    Return the remote branches that currently contain a commit.

    Important:
        Git does not permanently store the branch on which a commit
        was originally created. These branches only represent the
        remote references from which the commit is currently reachable.

    Args:
        repository: Path to the Git repository.
        commit_hash: Commit hash to inspect.

    Returns:
        Sorted list of remote branches containing the commit.
    """

    output = run_git(
        repository,
        [
            "for-each-ref",
            "--contains",
            commit_hash,
            "--format=%(refname:short)",
            REMOTE_REFS,
        ],
    )

    return normalize_remote_branches(output)


# ============================================================
# Report Generation
# ============================================================

def generate_reports(
    repository: Path,
    days: int,
) -> tuple[JsonDict, JsonDict]:
    """
    Generate author and repository activity reports.

    Args:
        repository: Path to the Git repository.
        days: Number of previous days included in the analysis.

    Returns:
        Tuple containing:
            - Author activity report.
            - Repository activity report.
    """

    commit_hashes = get_commits_in_period(
        repository,
        days,
    )

    remote_branches = get_remote_branches(
        repository
    )

    # Authors are grouped by normalized email address.
    authors: dict[str, JsonDict] = {}

    branch_commit_counts: defaultdict[str, int] = (
        defaultdict(int)
    )

    commit_details: list[JsonDict] = []

    # --------------------------------------------------------
    # Analyze each commit
    # --------------------------------------------------------

    for commit_hash in commit_hashes:

        commit = get_commit_metadata(
            repository,
            commit_hash,
        )

        commit_branches = get_commit_remote_branches(
            repository,
            commit_hash,
        )

        if not commit_branches:
            commit_branches = [
                NO_REMOTE_BRANCH
            ]

        commit["branches"] = commit_branches

        commit_details.append(commit)

        email = commit["email"]

        # Initialize the author accumulator the first time
        # an email address appears.
        if email not in authors:
            authors[email] = {
                "email": email,
                "names_used": set(),
                "commit_count": 0,
                "branches": defaultdict(int),
                "commits": [],
            }

        author = authors[email]

        author["names_used"].add(
            commit["author"]
        )

        author["commit_count"] += 1

        for branch in commit_branches:
            author["branches"][branch] += 1
            branch_commit_counts[branch] += 1

        author["commits"].append(
            {
                "hash": commit["hash"],
                "short_hash": commit["short_hash"],
                "date": commit["date"],
                "message": commit["message"],
                "branches": commit_branches,
            }
        )

    # --------------------------------------------------------
    # Build serializable author data
    # --------------------------------------------------------

    author_list: list[JsonDict] = []

    for author in authors.values():

        author_list.append(
            {
                "email": author["email"],
                "names_used": sorted(
                    author["names_used"]
                ),
                "commit_count": author[
                    "commit_count"
                ],
                "branches": dict(
                    sorted(
                        author["branches"].items(),
                        key=lambda item: (
                            -item[1],
                            item[0],
                        ),
                    )
                ),
                "commits": sorted(
                    author["commits"],
                    key=lambda commit: commit["date"],
                    reverse=True,
                ),
            }
        )

    # Authors with the highest commit count appear first.
    author_list.sort(
        key=lambda author: (
            -author["commit_count"],
            author["email"],
        )
    )

    # --------------------------------------------------------
    # Analysis period
    # --------------------------------------------------------

    end_date = datetime.now(
        timezone.utc
    )

    start_date = end_date - timedelta(
        days=days
    )

    period = {
        "days": days,
        "from": start_date.isoformat(),
        "to": end_date.isoformat(),
    }

    # --------------------------------------------------------
    # Author report
    # --------------------------------------------------------

    authors_report = {
        "period": period,
        "author_count": len(author_list),
        "authors": author_list,
        "branch_warning": (
            "The listed branches are the remote branches "
            "that currently contain each commit. Git does "
            "not store the original branch on which a commit "
            "was created."
        ),
    }

    # --------------------------------------------------------
    # Repository report
    # --------------------------------------------------------

    repository_report = {
        "period": period,
        "period_commit_count": len(
            commit_hashes
        ),
        "historical_commit_count": (
            get_total_commit_count(repository)
        ),
        "period_author_count": len(
            author_list
        ),
        "detected_remote_branches": (
            remote_branches
        ),
        "activity_by_branch": dict(
            sorted(
                branch_commit_counts.items(),
                key=lambda item: (
                    -item[1],
                    item[0],
                ),
            )
        ),
        "commits": sorted(
            commit_details,
            key=lambda commit: commit["date"],
            reverse=True,
        ),
        "warning": (
            "A commit may be counted under multiple branches "
            "when it is currently reachable from each of them."
        ),
    }

    return (
        authors_report,
        repository_report,
    )


# ============================================================
# JSON Output
# ============================================================

def save_json(
    path: Path,
    content: JsonDict,
) -> None:
    """
    Save a dictionary as a UTF-8 JSON file.

    Missing parent directories are created automatically.

    Args:
        path: Destination JSON file.
        content: Data to serialize.
    """

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        encoding="utf-8",
    ) as output_file:

        json.dump(
            content,
            output_file,
            ensure_ascii=False,
            indent=2,
        )

        # POSIX text files conventionally end with a newline.
        output_file.write("\n")


# ============================================================
# Command-Line Interface
# ============================================================

def parse_arguments() -> argparse.Namespace:
    """
    Parse command-line arguments.

    Returns:
        Parsed command-line arguments.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Generate JSON reports containing commit, author, "
            "and branch activity from a Git repository."
        )
    )

    parser.add_argument(
        "--repository",
        type=Path,
        required=True,
        help=(
            "Path to the Git repository that will be analyzed."
        ),
    )

    parser.add_argument(
        "--days",
        type=int,
        default=DEFAULT_ANALYSIS_DAYS,
        help=(
            "Number of previous days to analyze. "
            f"Default: {DEFAULT_ANALYSIS_DAYS}."
        ),
    )

    parser.add_argument(
        "--authors-output",
        type=Path,
        default=DEFAULT_AUTHORS_OUTPUT,
        help=(
            "Destination JSON file for the author report. "
            f"Default: {DEFAULT_AUTHORS_OUTPUT}."
        ),
    )

    parser.add_argument(
        "--repository-output",
        type=Path,
        default=DEFAULT_REPOSITORY_OUTPUT,
        help=(
            "Destination JSON file for the repository report. "
            f"Default: {DEFAULT_REPOSITORY_OUTPUT}."
        ),
    )

    return parser.parse_args()


# ============================================================
# Validation
# ============================================================

def validate_arguments(
    repository: Path,
    days: int,
) -> None:
    """
    Validate command-line input before performing the analysis.

    Args:
        repository: Repository path supplied by the user.
        days: Number of days requested for the analysis.

    Raises:
        ValueError: If an argument is invalid.
    """

    if days <= 0:
        raise ValueError(
            "--days must be greater than zero."
        )

    if not repository.exists():
        raise ValueError(
            f"Repository path does not exist: {repository}"
        )

    if not repository.is_dir():
        raise ValueError(
            f"Repository path is not a directory: {repository}"
        )

    if not (repository / ".git").exists():
        raise ValueError(
            f"The path does not appear to be a Git repository: "
            f"{repository}"
        )


# ============================================================
# Main Program
# ============================================================

def main() -> int:
    """
    Run the repository analysis and generate both JSON reports.

    Returns:
        Process exit code. Zero indicates success.
    """

    args = parse_arguments()

    repository = args.repository.resolve()

    authors_output = (
        args.authors_output.resolve()
    )

    repository_output = (
        args.repository_output.resolve()
    )

    try:
        # Validate everything before running Git commands.
        validate_arguments(
            repository,
            args.days,
        )

        authors_report, repository_report = (
            generate_reports(
                repository=repository,
                days=args.days,
            )
        )

        save_json(
            authors_output,
            authors_report,
        )

        save_json(
            repository_output,
            repository_report,
        )

    except (
        OSError,
        RuntimeError,
        ValueError,
    ) as error:

        print(
            f"Error: {error}",
            file=sys.stderr,
        )

        return 1

    print(
        "Reports generated successfully:"
    )

    print(
        f"- Authors: {authors_output}"
    )

    print(
        f"- Repository: {repository_output}"
    )

    print(
        "Commits found during the analysis period: "
        f"{repository_report['period_commit_count']}"
    )

    print(
        "Authors found during the analysis period: "
        f"{repository_report['period_author_count']}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())