"""
Persist FIS Grader reports in MongoDB Atlas.

This module reads the JSON reports generated by commit_report.py and persists
repository, author, commit, and analysis-run data in MongoDB.

The persistence strategy is idempotent:
- Repositories are upserted by group ID.
- Authors are upserted by normalized email address.
- Commits are upserted by repository ID and commit hash.
- Analysis runs are upserted by GitHub run ID, run attempt, and group ID.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from bson import ObjectId
from pymongo import MongoClient, UpdateOne
from pymongo.errors import PyMongoError
from pymongo.server_api import ServerApi


# ============================================================
# Configuration
# ============================================================

MONGODB_URI_ENV = "MONGODB_URI"
DEFAULT_DATABASE = "fis_grader"
MONGODB_TIMEOUT_MS = 10_000

JsonDict = dict[str, Any]
AuthorIdMap = dict[str, ObjectId]


# ============================================================
# Command-Line Interface
# ============================================================

def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Persist FIS Grader JSON reports in MongoDB Atlas."
        )
    )

    parser.add_argument(
        "--authors-report",
        type=Path,
        required=True,
        help="Path to the author report JSON file.",
    )

    parser.add_argument(
        "--repository-report",
        type=Path,
        required=True,
        help="Path to the repository report JSON file.",
    )

    parser.add_argument(
        "--group-id",
        required=True,
        help="Course group identifier, for example G1.",
    )

    parser.add_argument(
        "--repository",
        required=True,
        help=(
            "Full GitHub repository name, for example "
            "puj-course/FIS_2630_1204_G1."
        ),
    )

    parser.add_argument(
        "--database",
        default=DEFAULT_DATABASE,
        help=f"MongoDB database name. Default: {DEFAULT_DATABASE}.",
    )

    parser.add_argument(
        "--github-run-id",
        required=True,
        help="GitHub Actions run ID.",
    )

    parser.add_argument(
        "--github-run-attempt",
        type=int,
        required=True,
        help="GitHub Actions run attempt number.",
    )

    parser.add_argument(
        "--github-workflow",
        required=True,
        help="GitHub Actions workflow name.",
    )

    return parser.parse_args()


# ============================================================
# JSON Utilities
# ============================================================

def load_json(path: Path) -> JsonDict:
    """Load and return a JSON object from disk."""

    if not path.is_file():
        raise FileNotFoundError(
            f"Report file does not exist: {path}"
        )

    with path.open("r", encoding="utf-8") as file:
        content = json.load(file)

    if not isinstance(content, dict):
        raise ValueError(
            f"Expected a JSON object in {path}."
        )

    return content


def validate_reports(
    authors_report: JsonDict,
    repository_report: JsonDict,
) -> None:
    """Validate the minimum structure required for persistence."""

    if not isinstance(authors_report.get("period"), dict):
        raise ValueError(
            "Author report is missing the 'period' object."
        )

    if not isinstance(authors_report.get("authors"), list):
        raise ValueError(
            "Author report is missing the 'authors' list."
        )

    if not isinstance(repository_report.get("period"), dict):
        raise ValueError(
            "Repository report is missing the 'period' object."
        )

    if not isinstance(repository_report.get("commits"), list):
        raise ValueError(
            "Repository report is missing the 'commits' list."
        )

    required_repository_fields = (
        "period_commit_count",
        "historical_commit_count",
        "period_author_count",
        "detected_remote_branches",
        "activity_by_branch",
    )

    missing_fields = [
        field
        for field in required_repository_fields
        if field not in repository_report
    ]

    if missing_fields:
        raise ValueError(
            "Repository report is missing required fields: "
            + ", ".join(missing_fields)
        )


def parse_iso_datetime(value: str) -> datetime:
    """Parse an ISO-8601 timestamp and normalize it to UTC."""

    if not isinstance(value, str) or not value.strip():
        raise ValueError(
            f"Invalid ISO-8601 datetime value: {value!r}"
        )

    normalized = value.strip().replace("Z", "+00:00")

    try:
        parsed = datetime.fromisoformat(normalized)

    except ValueError as error:
        raise ValueError(
            f"Invalid ISO-8601 datetime value: {value}"
        ) from error

    if parsed.tzinfo is None:
        parsed = parsed.replace(
            tzinfo=timezone.utc
        )

    return parsed.astimezone(
        timezone.utc
    )


def utc_now() -> datetime:
    """Return the current timezone-aware UTC datetime."""

    return datetime.now(
        timezone.utc
    )


# ============================================================
# MongoDB Connection
# ============================================================

def create_mongodb_client() -> MongoClient[JsonDict]:
    """Create a MongoDB client and verify the Atlas connection."""

    mongodb_uri = os.getenv(
        MONGODB_URI_ENV
    )

    if not mongodb_uri:
        raise RuntimeError(
            f"Environment variable {MONGODB_URI_ENV} is not set."
        )

    client: MongoClient[JsonDict] = MongoClient(
        mongodb_uri,
        server_api=ServerApi("1"),
        serverSelectionTimeoutMS=MONGODB_TIMEOUT_MS,
    )

    # Fail early if credentials, network access,
    # or the connection URI are invalid.
    client.admin.command("ping")

    return client


# ============================================================
# Repository Persistence
# ============================================================

def upsert_repository(
    database: Any,
    group_id: str,
    repository_name: str,
) -> JsonDict:
    """Create or update the repository document and return it."""

    now = utc_now()

    database.repositories.update_one(
        {
            "group_id": group_id
        },
        {
            "$set": {
                "full_name": repository_name,
                "active": True,
                "updated_at": now,
            },
            "$setOnInsert": {
                "created_at": now,
            },
        },
        upsert=True,
    )

    repository = database.repositories.find_one(
        {
            "group_id": group_id
        }
    )

    if repository is None:
        raise RuntimeError(
            "Unable to retrieve repository document "
            f"for {group_id}."
        )

    return repository


# ============================================================
# Author Persistence
# ============================================================

def normalize_email(email: Any) -> str:
    """Normalize and validate an author email address."""

    if not isinstance(email, str) or not email.strip():
        raise ValueError(
            f"Invalid author email: {email!r}"
        )

    return email.strip().lower()


def upsert_authors(
    database: Any,
    authors_report: JsonDict,
) -> AuthorIdMap:
    """Upsert authors and return a mapping from email to ObjectId."""

    now = utc_now()

    operations: list[UpdateOne] = []
    emails: list[str] = []

    for author in authors_report["authors"]:

        if not isinstance(author, dict):
            raise ValueError(
                "Every entry in 'authors' must be a JSON object."
            )

        email = normalize_email(
            author.get("email")
        )

        raw_names = author.get(
            "names_used",
            [],
        )

        if not isinstance(raw_names, list):
            raise ValueError(
                f"'names_used' must be a list for author {email}."
            )

        names = sorted(
            {
                name.strip()
                for name in raw_names
                if isinstance(name, str)
                and name.strip()
            }
        )

        update: JsonDict = {
            "$set": {
                "updated_at": now,
                "last_seen_at": now,
            },
            "$setOnInsert": {
                "email": email,
                "created_at": now,
            },
        }

        if names:
            update["$addToSet"] = {
                "names_used": {
                    "$each": names,
                }
            }

        operations.append(
            UpdateOne(
                {
                    "email": email
                },
                update,
                upsert=True,
            )
        )

        emails.append(email)

    if operations:
        database.authors.bulk_write(
            operations,
            ordered=False,
        )

    author_ids: AuthorIdMap = {}

    if emails:
        documents = database.authors.find(
            {
                "email": {
                    "$in": list(set(emails))
                }
            },
            {
                "_id": 1,
                "email": 1,
            },
        )

        for document in documents:
            author_ids[
                document["email"]
            ] = document["_id"]

    missing_authors = sorted(
        set(emails)
        - set(author_ids)
    )

    if missing_authors:
        raise RuntimeError(
            "Unable to retrieve persisted authors: "
            + ", ".join(missing_authors)
        )

    return author_ids


# ============================================================
# Commit Persistence
# ============================================================

def upsert_commits(
    database: Any,
    repository_id: ObjectId,
    repository_report: JsonDict,
    author_ids: AuthorIdMap,
) -> int:
    """Upsert all commits contained in the repository report."""

    now = utc_now()

    operations: list[UpdateOne] = []

    for commit in repository_report["commits"]:

        if not isinstance(commit, dict):
            raise ValueError(
                "Every entry in 'commits' must be a JSON object."
            )

        commit_hash = commit.get("hash")

        if (
            not isinstance(commit_hash, str)
            or not commit_hash.strip()
        ):
            raise ValueError(
                "A commit is missing a valid 'hash'."
            )

        email = normalize_email(
            commit.get("email")
        )

        author_id = author_ids.get(
            email
        )

        if author_id is None:
            raise ValueError(
                "Commit references an author that is "
                "missing from the author report: "
                f"{email}"
            )

        raw_branches = commit.get(
            "branches",
            [],
        )

        if not isinstance(raw_branches, list):
            raise ValueError(
                "'branches' must be a list "
                f"for commit {commit_hash}."
            )

        branches = sorted(
            {
                branch.strip()
                for branch in raw_branches
                if isinstance(branch, str)
                and branch.strip()
            }
        )

        operations.append(
            UpdateOne(
                {
                    "repository_id": repository_id,
                    "hash": commit_hash.strip(),
                },
                {
                    "$set": {
                        "short_hash": commit.get(
                            "short_hash"
                        ),
                        "author_id": author_id,
                        "author_name": commit.get(
                            "author"
                        ),
                        "author_email": email,
                        "date": parse_iso_datetime(
                            commit.get("date")
                        ),
                        "message": commit.get(
                            "message",
                            "",
                        ),
                        "current_remote_branches": branches,
                        "updated_at": now,
                    },
                    "$setOnInsert": {
                        "created_at": now,
                    },
                },
                upsert=True,
            )
        )

    if operations:
        database.commits.bulk_write(
            operations,
            ordered=False,
        )

    return len(operations)


# ============================================================
# Analysis Run Persistence
# ============================================================

def build_authors_snapshot(
    authors_report: JsonDict,
) -> list[JsonDict]:
    """Create the historical author snapshot for an analysis run."""

    snapshot = []

    for author in authors_report["authors"]:

        email = normalize_email(
            author.get("email")
        )

        snapshot.append(
            {
                "email": email,
                "names_used": author.get(
                    "names_used",
                    [],
                ),
                "commit_count": author.get(
                    "commit_count",
                    0,
                ),
                "branches": author.get(
                    "branches",
                    {},
                ),
            }
        )

    return snapshot


def upsert_analysis_run(
    database: Any,
    repository_id: ObjectId,
    group_id: str,
    repository_name: str,
    authors_report: JsonDict,
    repository_report: JsonDict,
    github_run_id: str,
    github_run_attempt: int,
    github_workflow: str,
) -> ObjectId:
    """Persist one historical GitHub Actions analysis run."""

    now = utc_now()

    period = repository_report[
        "period"
    ]

    run_filter = {
        "source.github_run_id": github_run_id,
        "source.github_run_attempt": github_run_attempt,
        "group_id": group_id,
    }

    run_data = {
        "repository_id": repository_id,
        "group_id": group_id,
        "repository_name": repository_name,
        "executed_at": now,

        "period": {
            "days": period.get("days"),
            "from": parse_iso_datetime(
                period.get("from")
            ),
            "to": parse_iso_datetime(
                period.get("to")
            ),
        },

        "metrics": {
            "period_commit_count":
                repository_report[
                    "period_commit_count"
                ],

            "historical_commit_count":
                repository_report[
                    "historical_commit_count"
                ],

            "period_author_count":
                repository_report[
                    "period_author_count"
                ],
        },

        "detected_remote_branches":
            repository_report[
                "detected_remote_branches"
            ],

        "activity_by_branch":
            repository_report[
                "activity_by_branch"
            ],

        "authors_snapshot":
            build_authors_snapshot(
                authors_report
            ),

        "source": {
            "system": "github_actions",
            "workflow": github_workflow,
            "github_run_id": github_run_id,
            "github_run_attempt":
                github_run_attempt,
        },

        "updated_at": now,
    }

    database.analysis_runs.update_one(
        run_filter,
        {
            "$set": run_data,
            "$setOnInsert": {
                "created_at": now,
            },
        },
        upsert=True,
    )

    run = database.analysis_runs.find_one(
        run_filter,
        {
            "_id": 1
        },
    )

    if run is None:
        raise RuntimeError(
            "Unable to retrieve the persisted analysis run."
        )

    return run["_id"]


# ============================================================
# Repository Summary
# ============================================================

def update_repository_summary(
    database: Any,
    repository_id: ObjectId,
    repository_report: JsonDict,
) -> None:
    """Store the latest analysis summary in the repository document."""

    now = utc_now()

    database.repositories.update_one(
        {
            "_id": repository_id
        },
        {
            "$set": {
                "last_analysis_at": now,

                "latest_metrics": {
                    "period_commit_count":
                        repository_report[
                            "period_commit_count"
                        ],

                    "historical_commit_count":
                        repository_report[
                            "historical_commit_count"
                        ],

                    "period_author_count":
                        repository_report[
                            "period_author_count"
                        ],
                },

                "updated_at": now,
            }
        },
    )


# ============================================================
# Main Program
# ============================================================

def main() -> int:
    """Persist both reports and return a process exit code."""

    args = parse_arguments()

    client: MongoClient[JsonDict] | None = None

    try:
        authors_report = load_json(
            args.authors_report.resolve()
        )

        repository_report = load_json(
            args.repository_report.resolve()
        )

        validate_reports(
            authors_report,
            repository_report,
        )

        client = create_mongodb_client()

        database = client[
            args.database
        ]

        # ----------------------------------------------------
        # Repository
        # ----------------------------------------------------

        repository = upsert_repository(
            database=database,
            group_id=args.group_id,
            repository_name=args.repository,
        )

        repository_id = repository["_id"]

        # ----------------------------------------------------
        # Authors
        # ----------------------------------------------------

        author_ids = upsert_authors(
            database=database,
            authors_report=authors_report,
        )

        # ----------------------------------------------------
        # Commits
        # ----------------------------------------------------

        persisted_commit_count = (
            upsert_commits(
                database=database,
                repository_id=repository_id,
                repository_report=repository_report,
                author_ids=author_ids,
            )
        )

        # ----------------------------------------------------
        # Historical Analysis Run
        # ----------------------------------------------------

        analysis_run_id = (
            upsert_analysis_run(
                database=database,
                repository_id=repository_id,
                group_id=args.group_id,
                repository_name=args.repository,
                authors_report=authors_report,
                repository_report=repository_report,
                github_run_id=args.github_run_id,
                github_run_attempt=args.github_run_attempt,
                github_workflow=args.github_workflow,
            )
        )

        # ----------------------------------------------------
        # Latest Repository Summary
        # ----------------------------------------------------

        update_repository_summary(
            database=database,
            repository_id=repository_id,
            repository_report=repository_report,
        )

    except (
        FileNotFoundError,
        json.JSONDecodeError,
        KeyError,
        OSError,
        PyMongoError,
        RuntimeError,
        TypeError,
        ValueError,
    ) as error:

        print(
            f"Error: {error}",
            file=sys.stderr,
        )

        return 1

    finally:
        if client is not None:
            client.close()

    print(
        "MongoDB persistence completed successfully:"
    )

    print(
        f"- Group: {args.group_id}"
    )

    print(
        f"- Repository: {args.repository}"
    )

    print(
        f"- Database: {args.database}"
    )

    print(
        f"- Authors processed: {len(author_ids)}"
    )

    print(
        f"- Commits processed: {persisted_commit_count}"
    )

    print(
        f"- Analysis run ID: {analysis_run_id}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())