# 为了使工作完美,初始化变量时必须以大写字母开头

  # __________________________________________
  # v1.0.0
  # __________________________________________

  name: Calificador de estudiante 

  on:
    # Permite ejecutarlo manualmente.
    workflow_dispatch:

    # También puede ejecutarse automáticamente.
    schedule:
      # Todos los lunes a las 9:00 a. m. de Colombia.
      - cron: "0 14 * * 1"

  permissions:
    contents: read

  jobs:
    evaluar:
      name: Evaluar ${{ matrix.id }}
      runs-on: ubuntu-latest

      strategy:
      # En caso de que un estudiante tenga errores, no se detendrá la ejecución de los demás.
        fail-fast: false
        matrix:
          include:
            - id: G1
              repository: organizacion/fis-G1

            - id: G2
              repository: organizacion/fis-G2

            - id: G3
              repository: organizacion/fis-G3

            - id: G4
              repository: organizacion/fis-G4

            - id: G5
              repository: organizacion/fis-G5

      steps:
        # Descarga el repositorio con los archivos necesarios.
        - name: Descargar evaluador
          uses: actions/checkout@v7
          with:
            path: calificador

        # Descarga el repositorio del estudiante seleccionado por la matriz.
        - name: Descargar repositorio del estudiante
          uses: actions/checkout@v7
          with:
            repository: ${{ matrix.repository }}
            token: ${{ secrets.STUDENT_REPOS_TOKEN }}
            path: estudiante
            # descargar ultimo commit, 0 si queremos todo el historial
            fetch-depth: 1
            # run: git -C estudiante log --oneline
            persist-credentials: false

        - name: Configurar Python
          uses: actions/setup-python@v7
          with:
            python-version: "3.12"

        - name: Instalar dependencias
          run: |
            python -m pip install --upgrade pip
            python -m pip install openai

        - name: Verificar archivos requeridos
          run: |
           

        - name: Evaluar archivo con el deepseek
          env:
            DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
            STUDENT_ID: ${{ matrix.id }}
            STUDENT_REPOSITORY: ${{ matrix.repository }}
          run: |
           

        - name: Guardar resultado
          if: always()
          uses: actions/upload-artifact@v7
          with:
            name: resultado-${{ matrix.id }}
            path: resultado-${{ matrix.id }}.json
            if-no-files-found: warn